---
title: "Fundamental Solution to Laplace's Equation"
author: Edwin
format: html
toc: true
toc-depth: 3
toc-location: left
toc-expand: false
title-block-style: plain
title-block-banner: "#333333"
title-block-banner-color: "#fbfafa"
theme: cosmo 
editor: visual
css: laplaceinstyle.css
---

In this article, we shall derive a fundamental solution to Laplace's equation, which arises in many fields such as in differential geometry, electrostatics, and fluid mechanics.

## 1.1 Laplace's Equation

Laplace's equation is

$$
        -\Delta u=0.
$$ which is a special case of the more general Poisson's equation

$$
        -\Delta u=f.
$$

where $f$ is called the **source term**.

## 1.2 Physical Interpretation

Let $\vec F = -\text{grad}(u)$ be a smooth vector field defined on $\Omega \subseteq \mathbb{R}^n$. Suppose that the flux of $\vec F$ across the boundary $\partial \Omega$,

$$
\int_{\partial \Omega} \vec F \cdot \hat n \, dS,
$$

is negligible. By the Divergence, theorem, the flux (or boundary) integral is equivalent to the bulk (or domain) integral, so that

$$
        \int_{\partial\Omega}\vec F\cdot \hat n\,dS
        =
        \int_\Omega\text{div}(\vec F)\,d\vec x
        =0.
$$

Since

$$
  \begin{align}
        \text{div}(\vec F)
        &=\text{div}\big(-\text{grad}(u))\\[0.2cm]
        &=-\nabla\cdot\nabla u\\[0.2cm]
        &=-\nabla^2u\\[0.2cm]
        &=-\Delta u,
  \end{align}
$$ the integrand of the bulk term must satisfy

$$
  -\Delta u=0.
$$

In applications, $u$ may represent some kind of **density** or **potential**. For example, if $u$ represents

$$
        \displaystyle
        \begin{cases}
            \text{chemical concentration}\\
            \text{temperature}\\
            \text{electrostatic potential}.
        \end{cases}
$$ then $\vec F = -\text{grad}(u)$ is called

$$
        \displaystyle
        \begin{cases}
            \text{Fick's law}\\
            \text{Fourier's law of heat}\\
            \text{Ohm's law}.
        \end{cases}
$$

## 1.3 Strategy for Finding a Fundamental Solution

Laplace’s equation is a linear partial differential equation (**PDE**). To derive a fundamental solution, we exploit the symmetries of the **Laplace operator**.

The Laplacian is invariant under all **Euclidean transformations**, including:

-   rotations
-   translations
-   reflections

(All proofs left to the audience as an exercise).

Because of these symmetries, a fundamental solution centered at the origin must depend only on the **distance from the origin**, i.e., on $|x|$, and not on the direction.

## 1.4 Derivation of Fundamental Solution

Let $U=\mathbb R^n$ and $x=(x_1,x_2,...,x_n)$. Since the Laplacian in invariant under rotations, we begin by looking for **special** solutions of the form

$$
            u(x)=v(r),
$$

called **radial** solutions, where $$
  r=|x|=(x_1^2+x_2^2+\cdots+x_n^2)^{1/2}
$$

is the standard Euclidean norm.

For each $i=1,...,n$, we have

$$
  \begin{align}  
        \frac{\partial r}{\partial x_i}
        &=\frac{\partial}{\partial x_i}\bigg\{\;(x_1^2+x_2^2+\cdots+x_n^2)^{1/2}\;\bigg\}\\[0.2cm]
        &=\frac{1}{2}(x_1+x_2+\cdots+x_n)^{-1/2}\cdot(2x_i)\\[0.2cm]
        &=(x_1+x_2+\cdots+x_n)^{-1/2}\cdot x_i\\[0.2cm]
        &=\bigg((x_1+x_2+\cdots+x_n)^{1/2}\bigg)^{-1}\cdot x_i\\[0.2cm]
        &=(r)^{-1}\cdot x_i\\[0.2cm]
        &=\frac{x_i}{r}.
  \end{align}
$$ and

$$
        \begin{align}
        \frac{\partial}{\partial x_i}\bigg\{\frac{x_i}{r}\bigg\}
        &=\frac{\partial}{\partial x_i}\bigg \{x_i \cdot \frac{1}{r}\bigg\}\\[0.2cm]
        &=\frac{\partial}{\partial x_i}\big\{x_i\big\}\cdot\frac{1}{r} \;+\; x_i\cdot\frac{\partial}{\partial x_i}\bigg\{\frac{1}{r}\bigg\}\\[0.2cm]
        &=(1)\cdot\frac{1}{r} \;+\; x_i\cdot\frac{\partial}{\partial x_i}\{r^{-1}\}\\[0.2cm]
        &=\frac{1}{r} \;+\; x_i\cdot (-1)\,\cdot r^{-2}\cdot\frac{x_i}{r}\\[0.2cm]
        &=\frac{1}{r} \;-\; \frac{x_i^2}{r^3}.
        \end{align}
$$

Now, we assemble $\Delta u$.

#### $\bullet$ Getting $u_{x_i}$'s:

We have

$$
  \begin{align}
  \frac{\partial}{\partial x_i}u
  &=\frac{\partial}{\partial x_i} v
  =\frac{\partial v}{\partial r}\frac{\partial r}{\partial x_i}.
  \end{align}
$$ by chain rule.

Using subscript notation and letting $(\;'=\frac{\partial}{\partial r})$, we write

$$
  \begin{align}
  u_{x_i}
  &=v'(r)\frac{\partial r}{\partial x_i}
  =v'(r)\frac{x_i}{r}.
  \end{align}
$$

### $\bullet$ Getting $u_{x_ix_i}$'s:

Differentiate the previous line with respect to $x_i$ once more:

$$
  \begin{align}
  u_{x_ix_i}
  &=\frac{\partial}{\partial x_i}\bigg\{\,v'(r)\cdot\frac{x_i}{r}\,\bigg\}\\[0.2cm]
  &=\frac{\partial}{\partial x_i}\big\{\,v'(r)\,\big\}\cdot\frac{x_i}{r}\;+\;v'(r)\cdot\frac{\partial}{\partial x_i}\bigg\{\frac{x_i}{r}\bigg\}\\[0.2cm]
  &=v''(r)\,\frac{x_i^2}{r^2} \;+\; v'(r)\,\bigg(\frac{1}{r}-\frac{x_i^2}{r^3}\bigg).
  \end{align}
$$

### $\bullet$ Getting $\Delta u$:

To get $\Delta u$ we sum all $u_{x_ix_i}$'s for $i=1,...,n$:

$$
        \begin{align}
        \Delta u
        &=\sum_{i=1}^n u_{x_ix_i}\\[0.2cm]
        &=\sum_{i=1}^n\bigg\{\,v''(r)\frac{x_i^2}{r^2}
            \;+\;v'(r)\bigg(\frac{1}{r}-\frac{x_i^2}{r^3}\bigg)\,\bigg\}\\[0.2cm]
        &=\sum_{i=1}^n v''(r)\frac{x_i^2}{r^2}
        \;+\;\sum_{i=1}^n v'(r)\frac{1}{r}
        \;-\;\sum_{i=1}^n v'(r)\frac{x_i^2}{r^3}\\[0.2cm]
        &=\frac{v''(r)}{r^2}\sum_{i=1}^n x_i^2
            \;+\;\frac{nv'(r)}{r}
            \;-\;\frac{v'(r)}{r^3}\sum_{i=1}^n x_i^2\\[0.2cm]
        &=\frac{v''(r)}{r^2}\cdot r^2 
            \;+\;\frac{nv'(r)}{r}
            \;-\;\frac{v'(r)}{r^3}\cdot r^2\\[0.2cm]
        &=v''(r)\;+\;\frac{nv'(r)}{r}\;-\;\frac{v'(r)}{r}\\[0.2cm]
        \Delta u&=v''(r)+\frac{n-1}{r}v'(r).
        \end{align}
$$

Thus, $\Delta u = 0$ holds if and only if

$$
        v''(r)+\frac{n-1}{r}\,v'(r)=0 \quad\text{for}\quad r>0,
$$

which is a linear second order ordinary differential equation (**ODE**). We now focus on solving this ODE.

## 1.5 Solving the ODE in $r$

For the purposes of analysis, we first reduce the second order ODE to an equivalent first-order equation as follows:

$$
  \begin{align}
        v''+\frac{n-1}{r}v'&=0\\[0.2cm]
        \frac{v''}{v'}&=-\frac{n-1}{r}\\[0.2cm]
         \frac{v''}{v'}&=\frac{1-n}{r}\\[0.2cm]
        \implies\quad
        \log(|v'|)'&=\frac{1-n}{r}.
  \end{align}
$$

Integrating the last line once with respect to $r$ yields

$$
  \begin{align}
        \log(|v'|)
        &=(1-n)\log r+\text{constant}\\[0.2cm]\tag{by properties of logorithms}
        &=\log r^{(1-n)}+\text{constant}
  \end{align}
$$

Taking the exponential of this new expression further yields

$$
  \begin{align}
        |v'|&=\exp\big\{\;\log r^{(1-n)}+\text{constant}\;\big\}\\[0.2cm]\tag{by properties of exponents}
        &=\exp\big\{\log r^{(1-n)}\big\}\cdot\exp\{\;\text{constant}\;\}\\[0.2cm]
        \implies\quad
        v'&=Kr^{(1-n)}\\[0.2cm]
        &=Kr^{-(n-1)}\\[0.2cm]
        \implies\quad
        v'(r)&=\frac{K}{r^{n-1}},
  \end{align}
$$ for $K$ a constant.

We now proceed with the case analysis:

#### $\bullet$ Case $n=1$

We have

$$
        v'(r)=K.
$$ The solution consists of a family of straight lines. Namely, $$
        v(r)=Kr+L,
$$ for constants $K$ and $L$.

#### $\bullet$ Case $n=2$

In this case, the equation becomes

$$
        v'(r)=\frac{K}{r}
$$ which has the solution

$$
        v(r)=K\log r + L
        \quad\text{for}\quad
        r>0
$$ and constants $K$ and $L$.

#### $\bullet$ Case $n\ge3$

Notice that for

$$
\begin{aligned}
n=3:\quad\quad v'=\frac{K}{r^2} &\quad\implies\quad v=-\frac{K}{r}+\text{constant} \\[0.2cm]
n=4:\quad\quad v'=\frac{K}{r^3} &\quad\implies\quad v=-\frac{1}{2}\frac{K}{r^2}+\text{constant} \\[0.2cm]
n=5:\quad\quad v'=\frac{K}{r^4} &\quad\implies\quad v=-\frac{1}{3}\frac{K}{r^3}+\text{constant} \\[0.2cm]
n=6:\quad\quad v'=\frac{K}{r^5} &\quad\implies\quad v=-\frac{1}{4}\frac{K}{r^4}+\text{constant}\\[0.2cm]
n=7:\quad\quad v'=\frac{K}{r^6} &\quad\implies\quad v=-\frac{1}{5}\frac{K}{r^5}+\text{constant}\\[0.2cm]
n=8:\quad\quad v'=\frac{K}{r^7} &\quad\implies\quad v=-\frac{1}{6}\frac{K}{r^6}+\text{constant},
\end{aligned}
$$ and so on.

Thus, for $n\ge 3$, the solutions take the form

$$
        v(r)=-\frac{1}{n-2}\,\frac{K}{r^{n-2}} \;+\; L \quad\text{for}\quad r>0
$$

and constants $K$ and $L$.

## 1.6 Assembling Solutions

Putting all solutions together give us

$$
  \begin{align}
  \displaystyle
        v(r)=
        \begin{cases}
            Kr \;+\; L&\text{if}\quad\quad n=1\\[0.2cm]
            K\log r \;+\; L&\text{if}\quad\quad n=2\\[0.2cm]
            -\frac{1}{n-2}\,\frac{K}{r^{n-2}} \;+\; L&\text{if}\quad\quad n\ge3
        \end{cases}
    \end{align}
$$

for constants $K$ and $L$ and $x\in\mathbb R^n$ with $x\neq0$ whenever $n\ge 2$.

Since $r=|x|$, we may now represent the solution for the original dependent variable $u$ as

$$
  \begin{align}\displaystyle
        u(x)=
        \begin{cases}
            K|x| \;+\; L&\text{if}\quad\quad n=1\\[0.2cm]
            K\log|x| \;+\; L&\text{if}\quad\quad n=2\\[0.2cm]
            -\frac{1}{n-2}\,\frac{K}{|x|^{n-2}} \;+\; L&\text{if}\quad\quad n\ge3.
        \end{cases}
    \end{align}
$$

for $x\in\mathbb R^n$ with $x\neq0$ whenever $n\ge 2$.

## 1.7 The Fundamental Solution

It remains to find the constants $K$ and $L$.

**Claim**: There exists constants $K$ and $L$ such that the function $u(x)$ satisfies

$$
  -\Delta_x u = \delta_0,
$$ where $\delta_0$ denotes the **Dirac delta** at the origin.

Mathematically, it is a natural choice to define the Laplacian of $u$ at the origin as a Dirac delta because it captures the **singular behavior** of the solution when $n \ge 2$.

Physically, the Dirac delta models the **impulse response** of a system, i.e., the effect of a unit point source located at the origin, such as a point mass or a point charge.

#### $\bullet$ Finding $L$

The constant $L$ has no effect on the solution for all $n$. To see this, suppose we add a constant $L$ to the singular part of the solution:

$$
  u(x) = u_{\text{singular}}(x) + L.
$$

Then

$$
  \begin{align}
  -\Delta u 
  &= -\Delta (u_{\text{singular}} + L)\\[0.2cm]
  &= -\Delta u_{\text{singular}} - \Delta L\\[0.2cm]
  &= -\Delta u_{\text{singular}} - 0\\[0.2cm]
  &= -\Delta u_{\text{singular}}\\[0.2cm]
  \implies\quad
  -\Delta u
  &= \delta_0
  \end{align}
$$

Thus, adding $L$ does **not** change the Laplacian of the function $u$ and therefore does not affect the condition $-\Delta u = \delta_0$, so we **set** $L=0$ to simplify the formula.

#### $\bullet$ Finding $K$

We shall focus on finding $K$ for the case when $n=2$. We make use of the condition

$$
-\Delta u = \delta_0.
$$

by integrating both sides over a small ball $B_\varepsilon$ centered at the origin:

$$
\int_{B_\varepsilon} -\Delta u \, dx
=
\int_{B_\varepsilon} \delta_0 \, dx.
$$

By the defining property of the Dirac delta,

$$
\int_{B_\varepsilon} \delta_0 \, dx = 1,
$$

so

$$
\int_{B_\varepsilon} -\Delta u \, dx = 1.
$$

By the divergence theorem $$
\int_{B_\varepsilon} -\Delta u \, dx
=
-
\int_{\partial B_\varepsilon}
\frac{\partial u}{\partial n} \, dS.
$$

Thus we obtain the normalization condition $$
-\int_{\partial B_\varepsilon}
\frac{\partial u}{\partial n} \, dS = 1.
$$

For $n=2$, we take $$
u(x)=K\log|x|.
$$

Since the solution is radial, $$
\frac{\partial u}{\partial n} = \frac{\partial}{\partial r}\big\{K\log r\big\}=\frac{K}{r}.
$$

On $\partial B_\varepsilon$ we have $r=\varepsilon$, so

$$
\frac{\partial u}{\partial n}=\frac{K}{\varepsilon}.
$$

Since the circumference of $\partial B_\varepsilon$ is $2\pi\varepsilon$, the boundary integral becomes

$$
-\int_{\partial B_\varepsilon}
\frac{\partial u}{\partial n} \, dS
=-\frac{K}{\varepsilon}\int_{\partial B_\varepsilon}dS
=
-\frac{K}{\varepsilon}\cdot(2\pi\varepsilon)
=
-2\pi K.
$$

Therefore $$
-2\pi K = 1,
$$

or

$$
K = -\frac{1}{2\pi}.
$$

We can now define

$$
  \Phi(x) =
  \begin{cases}
    -\dfrac{1}{2}|x| & \text{if} \quad\quad n = 1,\\[0.2cm]
  -\dfrac{1}{2\pi} \log|x| & \text{if} \quad\quad n = 2,\\[0.2cm]
  \dfrac{1}{n(n-2)\,\alpha(n)} \dfrac{1}{|x|^{\,n-2}} & \text{if}  \quad\quad n \ge 3,
  \end{cases}
  \quad\quad
  x \in \mathbb{R}^n - \{0\},
$$ where $\alpha(n)$ is the volume of the unit ball in $\mathbb{R}^n$.

$\Phi$ is called a **fundamental solution** of the Laplacian.
